server {
    listen 8080;
    listen 8081;
    root /home/mlaussel/webserv/server_files/; 

    client_max_body_size 1000000;
    
    location /upload {
        methods GET POST DELETE;
        autoindex off;
        upload_dir /home/mlaussel/webserv/server_files/;
        cgi_setup .php /usr/bin/php-cgi;
    }

    location / {
        methods GET POST DELETE;
        index html/index.html;
        autoindex on;
        upload_dir /home/mlaussel/webserv/server_files/;
        cgi_setup .php /usr/bin/php-cgi;
    }

    location /test {
        methods GET POST DELETE;
        upload_dir /home/mlaussel/webserv/server_files/;
        autoindex on;
    }
    location /not {
        methods DELETE;
        upload_dir /home/mlaussel/webserv/server_files/;
        autoindex on;
    }
}