server {
    listen 8080;
    root /Users/mathildelaussel/webserv/www/html; 
    client_max_body_size 1000000;
    
	location / {
        index index.html;
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /upload {
        allow_methods GET POST DELETE;
        upload_dir /Users/mathildelaussel/webserv/www/html;
    }
}