server {
    listen 8080;
    listen 8081;
    root /home/mlaussel/webserv/server_files/; 
    error_page 400 /html/400.html;
    error_page 403 /html/403.html;
    error_page 404 /html/404.html;
    error_page 405 /html/405.html;
    error_page 413 /html/413.html;
    error_page 500 /html/500.html;
    client_max_body_size 1000000;
    
    location /upload {
        methods GET POST DELETE;
        upload_dir /home/mlaussel/webserv/server_files/;
        cgi_setup .php /usr/bin/php-cgi;
    }

    location / {
        methods GET POST DELETE ;
        index html/index.html;
        autoindex on;
        upload_dir /home/mlaussel/webserv/server_files/;
        cgi_setup .php /usr/bin/php-cgi;
    }

    location /test {
        methods GET POST DELETE;
        upload_dir /home/mlaussel/webserv/server_files/;
        autoindex on;
    }
}