server {
    listen 8080;
    root /home/lulussi/42/webserv2/www/html; 
    client_max_body_size 1000000;
    
	location / {
        index index.html;
       	methods GET POST DELETE;
        autoindex off;
    }

    location /upload {
        methods GET POST DELETE;
        upload_dir /home/lulussi/42/webserv2/www/html;
		cgi_setup ..py usr/bin/python3;
    }
}